### ISSUE TITLE
License change from MIT to GPLv3

### ISSUE THREAD

**Issue by ratoaq2** [angular-redux2/store#15]
I noticed that version 4.0.4 was released under MIT license and the new version 5.x updated the license to GPLv3.
Is the new upcoming release no longer be licensed under MIT conditions?

**Comment by Garefild** [comment]
Mozilla Public License 2.0 (MPL-2.0)  is more suitable for what I want.
I think I'll go with that.

 I will update you in the chat on what the license will be.
I'm leaving it open for now in case there are responses from other people.

**Comment by robertbradleyux** [comment]
@Garefild considering everybody using your library is likely moving to it from @angular-redux/store, it seems like it would make more sense to keep the MIT license which @angular-redux/store is already using in order to avoid a whole bunch of potential red-tape in getting adopters companies to approve the new licensing choice.

I see you said MPL-2.0 is more suitable for what you want, but what is it that you want? My understanding was that everybody on @angular-redux/store should be moving over to @angular-redux2/store. Is that not the case?

**Comment by Garefild** [comment]
> I see you said MPL-2.0 is more suitable for what you want, but what is it that you want?

If a company updates the library's code and adds features, it will be obliged to publish it for the benefit of all.
And this is a key difference between MIT and MPL-2.0.

I talked about it extensively in the chat.

**Comment by robertbradleyux** [comment]
Makes sense. Thanks for the response, I was just curious as I'm not familair with the MPL-2.0 license.

> I talked about it extensively in the chat.

Where is this chat? I have some other questions I'd like to ask (not related to licensing) if that would be a better place.

**Comment by Garefild** [comment]
https://discord.gg/QUWU9Mad
